"""Migrate the user table to conform to the resource system

Revision ID: 0bb1586e5014
Revises: 4e61785aa551
Create Date: 2021-07-30 04:01:20.751862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb1586e5014'
down_revision = '4e61785aa551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('user') as bop:
        bop.alter_column('password_hash', new_column_name='password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as bop:
        bop.alter_column('password', new_column_name='password_hash')

    op.drop_table('resource')
    # ### end Alembic commands ###
