"""Create a SalesOrder resource type

Revision ID: 0c66efcf3f4a
Revises: 3c547fb2bc42
Create Date: 2021-08-09 00:43:12.841315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c66efcf3f4a'
down_revision = '3c547fb2bc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order',
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('base_price_amount', sa.Integer(), nullable=True),
    sa.Column('base_price_currency', sa.String(), nullable=True),
    sa.Column('hourly_price_amount', sa.Integer(), nullable=True),
    sa.Column('hourly_price_currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['opportunity'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesorder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sales_order', ['salesorder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('salesorder_id')

    op.drop_table('sales_order')
    # ### end Alembic commands ###
