"""Allow Resource Log entries without subject

Revision ID: fbd468ade272
Revises: 41688513ac93
Create Date: 2021-08-23 15:23:53.093673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbd468ade272'
down_revision = '41688513ac93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_log', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_log', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
